Set up retrofit
AmrAbuelhamd/Weather-Map pull request #2
Opened 2021-05-04 12:24 UTC by AmrAbuelhamd

2021-05-05 01:22 UTC, AlexeiYakimov requested changes

2021-05-05 01:22 UTC, AlexeiYakimov commented on app/src/main/AndroidManifest.xml
> +        >
Не стоит таким  образом переносить тег, это неправильное форматирование. Лучше оставить как было.

2021-05-05 01:22 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/app/di/data/WeatherApiModule.kt
> +    factory {
В данном случае лучше сделать `single`, поскольку в приложении всегда нужен http-клиент, без него оно теряет смысл.
Конструировать такой экземпляр каждый раз, когда он нужен - большое расточительство ресурсов.

2021-05-05 01:22 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/app/di/data/WeatherApiModule.kt
> +                ).addInterceptor { chain ->
Интерсептор лучше объявить отдельно и инжектить через DI сюда.
Код перехватчика потенциально может очень сильно вырасти, и совсем не дело объявлять его там же, где объявляется собственно сам Retrofit.
Кроме того, если получать интерсептор через DI, можно иметь разные его реализации и быстро подменять по необходимости.

2021-05-05 01:22 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/app/di/data/WeatherApiModule.kt
> +                Json {
Экземпляр Json лучше иметь один на все приложение, чтобы правила сериализации/десериализации были одними и теми же - просто инициализируй его в модуле и получай через DI.

2021-05-05 01:22 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/app/utils/Connectivity.kt
> +class Connectivity constructor(
Необходимо создать интерфейс и оперировать именно интерфейсом, создавая в DI конкретную реализацию.
Это основной принцип - зависимости должны быть от абстракций, а не от реализаций.

2021-05-05 01:22 UTC, AlexeiYakimov commented on data/build.gradle
> +
Пустая строка здесь ни к чему.

2021-05-05 01:22 UTC, AlexeiYakimov commented on data/src/main/java/com/blogspot/soyamr/data/net/models/CityWeatherResponse.kt
> +data class CityWeatherResponse(
Лучше все параметры сделать `nullable`, поскольку никогда не можешь быть уверен, что тебе придет в ответ от сервиса. И если вдруг какой-то параметр не придет, приложение упадет с ошибкой десериализации.

2021-05-06 01:39 UTC, AlexeiYakimov requested changes

2021-05-06 01:39 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/app/utils/ConnectivityImpl.kt
> +                actNw.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> true
Все условия, при которых возвращается `true`, стоит совместить через логическое ИЛИ:
```
actNw.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) || trueactNw.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) ||
//for other device how are able to connect with Ethernet
actNw.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET) ||
//for check internet over Bluetooth
actNw.hasTransport(NetworkCapabilities.TRANSPORT_BLUETOOTH) -> true
```

2021-05-06 01:39 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/MainActivity.kt
> +        GlobalScope.launch {
`GlobalScope` использовать крайне не рекомендуется https://elizarov.medium.com/the-reason-to-avoid-globalscope-835337445abc

Здесь должна быть viewmodel, из которой нужно вызывать этот код.

2021-05-06 01:39 UTC, AlexeiYakimov commented on data/src/main/java/com/blogspot/soyamr/data/converters/ApiResponseConverters.kt
> +        main?.humidity ?: 999,
Здесь, как и договаривались, для всех цифр будем подставлять 0 - именно 0 является значением по умолчанию для простых числовых типов.
Сейчас в коде где-то 999, а где-то 0.

2021-05-06 01:39 UTC, AlexeiYakimov commented on data/src/main/java/com/blogspot/soyamr/data/net/interceptors/InternetExceptionInterceptor.kt
> +    private val noInternetConnectionString: String
Как уже обсуждали, нельзя передавать сюда строку: при изменении языка в Android эта строка останется в той локали, которая была на момент запуска процесса приложения.

Договорились, что заведем специальное исключение `NoInternetException : IOException(…)`, которое будем кидать отсюда. И уже в app-слое сопоставим тип исключения с текстом.

2021-05-06 02:03 UTC, AmrAbuelhamd commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/MainActivity.kt
> +        GlobalScope.launch {
спасибо за статью я исправлю эту проблему на следующем этапе проекта.

2021-05-06 02:05 UTC, AlexeiYakimov approved these changes

2021-05-06 02:06 UTC, merged