Map clicks
AmrAbuelhamd/Weather-Map pull request #4
Opened 2021-05-11 03:38 UTC by AmrAbuelhamd

apk link
https://github.com/AmrAbuelhamd/Weather-Map/blob/map_clicks/app-debug%20v3.apk

2021-05-11 04:23 UTC, AlexeiYakimov requested changes

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +        if(Geocoder.isPresent()) {
После `if` не хватает пробела. Код не отформатирован согласно конвенции https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +                    geocoder.getFromLocation(latLng.latitude, latLng.longitude, 1)
Согласно документации данный код лучше выполнять не в UI-потоке, так как он занимает время.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +                binding.floatingCityInfoContainer.isVisible = true
Все вещи такого рода должны рулиться через DataBinding, поскольку у нас MVVM.
Здесь у нас совсем нет вьюмодели, и весь код находится во фрагменте.
Нам следует вынести установку видимости элементов и данных во вьюмодель, и использовать там DataBinding.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +
Две пустые строки: на самом деле здесь не требуется ни одной.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +                e.printStackTrace()
Было бы неплохо показать ошибку пользователю. Например, в Тосте.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +        }else{
Код не отформатирован согласно конвенции.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +
Лишняя пустая строка.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/utils/Utils.kt
> +
Лишняя пустая строка.

2021-05-11 04:23 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/utils/Utils.kt
> +fun getLocationAsDMS(location: Location, decimalPlace: Int): String {
Все методы из этого исходника попадут в глобальную область видимости приложения.
Едва ли нам это требуется.
Следует обернуть их в объект: `object Utils`

Кроме того, сам по себе метод `getLocationAsDMS` скорее всего нужен будет лишь во вьюмодели фрагмента с картой, так как выполняет очень специфичную работу.

2021-05-17 01:43 UTC, AlexeiYakimov requested changes

2021-05-17 01:43 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsFragment.kt
> +                false // is it okay to change variables of viewModel like this?!
В целом - это позволительно, но лучше создать во вьюмодели метод (например, `switchProgressBarVisibility(boolean)`) и вызывать его.

2021-05-17 01:43 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsViewModel.kt
> +    val cityInfoContainerVisibility: MutableLiveData<Boolean> = MutableLiveData(false)
Публичное поле `MutableLiveData` видно извне, а значит любой может изменить состояние вьюмодели. Чтобы этого не было, стоит воспользоваться паттерном, который у тебя уже применяется ниже  -  `_errorMessage`
Тогда состояние мы сможем менять только из самой вьюмодели, а снаружи будет видна абстрактная ливдата.

2021-05-17 01:43 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsViewModel.kt
> +            withContext(Dispatchers.Main) {
Этот метод переключает контекст, то есть ты запускаешь корутину на диспетчере `Dispatchers.IO`, но весь код все равно выполняется на `Dispatchers.Main`, см. https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-context.html
Чтобы поправить здесь дела, нужно выполнять на `Dispatchers.Main` только тот код, который устанавливает значения ливдаты. А можно сделать еще проще - устанавливать значение через метод https://developer.android.com/reference/android/arch/lifecycle/LiveData#postValue(T)

В этом случае переключение контекста не требуется вовсе.

2021-05-17 01:43 UTC, AlexeiYakimov commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsViewModel.kt
> +        formattedCoordinates = formattedCoordinates.replaceFirst(":".toRegex(), "'")
Повторение предыдущей строки.

2021-05-17 02:31 UTC, AmrAbuelhamd commented on app/src/main/java/com/blogspot/soyamr/weathermap/presentation/map/MapsViewModel.kt
> +        formattedCoordinates = formattedCoordinates.replaceFirst(":".toRegex(), "'")
это не то же самое, так как я чан во втором вхождении " : " в " ' "

2021-05-17 02:32 UTC, AlexeiYakimov approved these changes

2021-05-17 02:32 UTC, merged